### ISSUE TITLE
Chapter 9 Design Patterns 404 Link Referencing Views chapter

### ISSUE THREAD

**Issue by matthewcreek** [LaunchCodeEducation/csharp-web-dev-curriculum#73]
[Relevant link](https://education.launchcode.org/csharp-web-dev-curriculum/asp-net-intro/reading/asp-dotnet-intro/index.html#how-we-teach-aspnet)

Text states: "The following video is the first in a series designed to help you code your first ASP.NET application. We will be building this app over the next several chapters, finishing in [Views chapter](https://education.launchcode.org/csharp-web-dev-curriculum/asp-net-intro/reading/asp-dotnet-intro/LINK)."

"Views chapter" link does not lead anywhere.

**Comment by gildedgardenia** [comment]
Thank you! Deployed a fix today!
